version: '3.8'

services:
  frontend:
    build: 
      context: ./frontend
    ports:
      - "${FRONTEND_PORT}:80"
    volumes:
      - ./frontend/src:/app/src  # Only for development
    environment:
      - BACKEND_URL=http://${DOCKER_HOST_IP}:${BACKEND_PORT}
    depends_on:
      - backend
    #command: npm run start  # Adjust this as per your frontend's start command

  backend:
    build:
      context: ./backend
      target: production
    environment:
      - DATABASE_URL=postgres://user:password@db:${DB_PORT}/hammervision
    ports:
      - "${BACKEND_PORT}:3001"
    depends_on:
      - db
  db:
    image: postgres
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "${DB_PORT}:5432"
  backend-test:
    build:
      context: ./backend
      target: test

volumes:
  db-data:
