version: '3.8'
services:
  frontend:
    build: 
      context: ./frontend
    ports:
      - "8080:80"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      target: production
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/hammervision
    ports:
      - "3001:3001"
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_DB=hammervision
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend-test:
    build:
      context: ./backend
      target: test

volumes:
  db-data: